/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-09-15 01:37:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardItem_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/sts3_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Day04_Board_ju/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/sts3_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Day04_Board_ju/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1757403558891L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <title>Title</title>\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\n");
      out.write("          integrity=\"sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr\" crossorigin=\"anonymous\">\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("            integrity=\"sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q\"\n");
      out.write("            crossorigin=\"anonymous\"></script>\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"\n");
      out.write("            integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\" crossorigin=\"anonymous\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"/boards/boardItem.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div class=\"container\">\n");
      out.write("    <form id=\"modifyFrm\" action=\"/board/update\">\n");
      out.write("        <input type=\"hidden\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("        <div class=\"row title\">\n");
      out.write("            <div class=\"col divTitle\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("            <input type=\"hidden\" name=\"title\">\n");
      out.write("        </div>\n");
      out.write("        <hr>\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col writer\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <div class=\"col writeDate\">");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("|\n");
      out.write("                조회: ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.viewCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("        </div>\n");
      out.write("        <hr>\n");
      out.write("        <div class=\"row contents\">\n");
      out.write("            <div class=\"col divContents\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</div>\n");
      out.write("            <input type=\"hidden\" name=\"contents\">\n");
      out.write("        </div>\n");
      out.write("    </form>\n");
      out.write("    <hr>\n");
      out.write("    <div class=\"row fileContainer\">\n");
      out.write("        <div class=\"col\">\n");
      out.write("            <a href=\"/download.file\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${file.oriName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"row sideMenu m-0 p-0\">\n");
      out.write("        <div class=\"col m-0 p-0\" align=\"right\">\n");
      out.write("            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("            <button id=\"backBtn\" type=\"button\" class=\"btn btn-secondary\"\n");
      out.write("                    onclick=\"location.href='/board/list'\">목록으로\n");
      out.write("            </button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <hr>\n");
      out.write("    <form action=\"/reply/insert\" id=\"commentFrm\" method=\"post\">\n");
      out.write("        <div class=\"row leave-comment\">\n");
      out.write("            <div class=\"col-10 comment-contents\">\n");
      out.write("                <div class=\"form-control\" contenteditable=\"true\" data-placeholder=\"댓글을 입력하세요.\"></div>\n");
      out.write("                <input type=\"hidden\" id=\"comment-contents\" name=\"comment\">\n");
      out.write("                <input type=\"hidden\" name=\"parentSeq\">\n");
      out.write("                <input type=\"hidden\" name=\"writer\">\n");
      out.write("            </div>\n");
      out.write("            <div class=\"col-2\">\n");
      out.write("                <button class=\"btn btn-outline-primary\" id=\"comment-submit\" type=\"button\">등록</button>\n");
      out.write("                <script>\n");
      out.write("                    $(\"#comment-submit\").on(\"click\", function () {\n");
      out.write("                        $(\"#comment-contents\").val($(\".comment-contents div.form-control\").html());\n");
      out.write("\n");
      out.write("                        let params = new URLSearchParams(window.location.search);\n");
      out.write("                        $(\"[name = parentSeq]\").val(params.get(\"id\"));\n");
      out.write("                        $(\"#commentFrm\").submit();\n");
      out.write("                    });\n");
      out.write("                </script>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </form>\n");
      out.write("    <hr class=\"mb-1\">\n");
      out.write("    <div class=\"row comments m-0\">\n");
      out.write("        <script>\n");
      out.write("            let replyList = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reply}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("            let loginId = \"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\";\n");
      out.write("\n");
      out.write("            for (let reply of replyList) {\n");
      out.write("                let row = $(\"<div>\").addClass(\"row p-0\");\n");
      out.write("                row.css(\"margin-left\", \"10px\");\n");
      out.write("\n");
      out.write("                let writer = $(\"<div>\").addClass(\"row m-0 p-0\").html(reply.writer);\n");
      out.write("                writer.css(\"font-family\", \"Maruburi-Bold\");\n");
      out.write("\n");
      out.write("                let contents = $(\"<div>\").addClass(\"row p-0 replyContents\").html(reply.contents);\n");
      out.write("                contents.css({\"font-size\": \"12px\", \"margin-left\": \"5px\"});\n");
      out.write("\n");
      out.write("                let footer = $(\"<div>\").addClass(\"row m-0 p-0\");\n");
      out.write("                let writeDate = $(\"<div>\").addClass(\"col-6 p-0\").html(milliToDate(reply.writeDate));\n");
      out.write("                writeDate.css({\"font-size\": \"10px\", \"margin-bottom\": \"5px\"});\n");
      out.write("\n");
      out.write("                footer.append(writeDate);\n");
      out.write("\n");
      out.write("                if (reply.writer === loginId) {\n");
      out.write("                    let btnGroup = $(\"<div>\").addClass(\"col-6 modifyBtnGroup\");\n");
      out.write("\n");
      out.write("                    let modifyBtn = $(\"<button>\").addClass(\"btn btn-outline-secondary modifyBtn\");\n");
      out.write("                    modifyBtn.html(\"수정\");\n");
      out.write("\n");
      out.write("                    let modifyConfirmBtn = $(\"<button>\").addClass(\"btn btn-outline-success modifyConfirmBtn\");\n");
      out.write("                    modifyConfirmBtn.attr(\"type\", \"button\");\n");
      out.write("                    modifyConfirmBtn.html(\"완료\");\n");
      out.write("\n");
      out.write("                    let modifyCancelBtn = $(\"<button>\").addClass(\"btn btn-outline-danger modifyCancelBtn\");\n");
      out.write("                    modifyCancelBtn.attr(\"type\", \"button\");\n");
      out.write("                    modifyCancelBtn.html(\"취소\");\n");
      out.write("\n");
      out.write("                    let deleteBtn = $(\"<button>\").addClass(\"btn btn-outline-danger deleteBtn\");\n");
      out.write("                    deleteBtn.html(\"삭제\");\n");
      out.write("\n");
      out.write("                    modifyBtn.on(\"click\", () => {\n");
      out.write("                        modifyCancelBtn.css(\"display\", \"inline-block\");\n");
      out.write("                        modifyConfirmBtn.css(\"display\", \"inline-block\");\n");
      out.write("                        modifyBtn.css(\"display\", \"none\");\n");
      out.write("                        deleteBtn.css(\"display\", \"none\");\n");
      out.write("\n");
      out.write("                        contents.attr(\"contenteditable\", \"true\");\n");
      out.write("                        contents.addClass(\"form-control\");\n");
      out.write("                    });\n");
      out.write("\n");
      out.write("                    modifyConfirmBtn.on(\"click\", () => {\n");
      out.write("                        updateReply(reply, contents.html());\n");
      out.write("                    });\n");
      out.write("\n");
      out.write("                    modifyCancelBtn.on(\"click\", () => {\n");
      out.write("                        location.reload();\n");
      out.write("                    });\n");
      out.write("\n");
      out.write("                    deleteBtn.on(\"click\", () => {\n");
      out.write("                        deleteReply(reply);\n");
      out.write("                    });\n");
      out.write("\n");
      out.write("                    btnGroup.append(modifyBtn);\n");
      out.write("                    btnGroup.append(modifyConfirmBtn);\n");
      out.write("                    btnGroup.append(modifyCancelBtn);\n");
      out.write("                    btnGroup.append(deleteBtn);\n");
      out.write("\n");
      out.write("                    footer.append(btnGroup);\n");
      out.write("                }\n");
      out.write("\n");
      out.write("                row.append(writer);\n");
      out.write("                row.append(contents);\n");
      out.write("                row.append(footer);\n");
      out.write("\n");
      out.write("                $(\".comments\").append(row);\n");
      out.write("                $(\".comments\").append($(\"<hr>\").addClass(\"mb-1\"));\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function updateReply(reply, modifiedContents) {\n");
      out.write("                let params = new URLSearchParams(window.location.search);\n");
      out.write("                let seq = $(\"<input>\").attr({\"type\": \"hidden\", \"name\": \"seq\"}).val(reply.seq);\n");
      out.write("                let contents = $(\"<input>\").attr({\"type\": \"hidden\", \"name\": \"contents\"}).val(modifiedContents);\n");
      out.write("                let writer = $(\"<input>\").attr({\"type\": \"hidden\", \"name\": \"writer\"}).val(reply.writer);\n");
      out.write("                let parentSeq = $(\"<input>\").attr({\"type\": \"hidden\", \"name\": \"parentSeq\"}).val(params.get(\"id\"));\n");
      out.write("                let updateFrm = $(\"<form>\").attr({\"action\": \"/reply/update\", \"method\": \"post\"});\n");
      out.write("\n");
      out.write("                updateFrm.append(seq, writer, parentSeq, contents);\n");
      out.write("                $(document.body).append(updateFrm);\n");
      out.write("                updateFrm.submit();\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function deleteReply(reply) {\n");
      out.write("                let params = new URLSearchParams(window.location.search);\n");
      out.write("                let seq = $(\"<input>\").attr({\"type\": \"hidden\", \"name\": \"seq\"}).val(reply.seq);\n");
      out.write("                let writer = $(\"<input>\").attr({\"type\": \"hidden\", \"name\": \"writer\"}).val(reply.writer);\n");
      out.write("                let parentSeq = $(\"<input>\").attr({\"type\": \"hidden\", \"name\": \"parentSeq\"}).val(params.get(\"id\"));\n");
      out.write("                let deleteFrm = $(\"<form>\").attr({\"action\": \"/reply/delete\", \"method\": \"post\"});\n");
      out.write("\n");
      out.write("                deleteFrm.append(seq, writer, parentSeq);\n");
      out.write("                $(document.body).append(deleteFrm);\n");
      out.write("                deleteFrm.submit();\n");
      out.write("            }\n");
      out.write("\n");
      out.write("            function milliToDate(millis) {\n");
      out.write("                let date = new Date(millis);\n");
      out.write("                let year = date.getFullYear();\n");
      out.write("                let month = date.getMonth() + 1;\n");
      out.write("                let day = date.getDate();\n");
      out.write("\n");
      out.write("                return year + \".\" + month + \".\" + day;\n");
      out.write("            }\n");
      out.write("        </script>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f0.setParent(null);
    // /WEB-INF/views/board/boardItem.jsp(30,39) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.writeDate}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/views/board/boardItem.jsp(30,39) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd hh:mm");
    int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/board/boardItem.jsp(47,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.writer == sessionScope.loginId}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\n");
        out.write("                <button id=\"modifyBtn\" type=\"button\" class=\"btn btn-outline-success\">수정</button>\n");
        out.write("\n");
        out.write("                <button id=\"deleteBtn\" type=\"button\" class=\"btn btn-danger\" data-bs-toggle=\"modal\"\n");
        out.write("                        data-bs-target=\"#deletePost\">삭제\n");
        out.write("                </button>\n");
        out.write("\n");
        out.write("                <div class=\"modal fade\" id=\"deletePost\" tabindex=\"-1\" aria-labelledby=\"deletePost\" aria-hidden=\"true\">\n");
        out.write("                    <div class=\"modal-dialog\">\n");
        out.write("                        <div class=\"modal-content\">\n");
        out.write("                            <div class=\"modal-header\">\n");
        out.write("                                <h5>정말 삭제 하시겠습니까?</h5>\n");
        out.write("                            </div>\n");
        out.write("                            <div class=\"modal-footer\">\n");
        out.write("                                <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">아니요</button>\n");
        out.write("                                <button type=\"button\"\n");
        out.write("                                        onclick=\"location.href = '/board/delete?id=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&writer=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("'\"\n");
        out.write("                                        class=\"btn btn-primary\">예\n");
        out.write("                                </button>\n");
        out.write("                            </div>\n");
        out.write("                        </div>\n");
        out.write("                    </div>\n");
        out.write("                </div>\n");
        out.write("\n");
        out.write("                <button id=\"confirmBtn\" class=\"btn btn-success d-none\">수정완료</button>\n");
        out.write("                <button id=\"cancelBtn\" class=\"btn btn-danger d-none\">취소</button>\n");
        out.write("\n");
        out.write("                <script>\n");
        out.write("                    $(\"#modifyBtn\").on(\"click\", function () {\n");
        out.write("                        $(\"#confirmBtn, #cancelBtn\").toggleClass(\"d-none\", false);\n");
        out.write("                        $(\"#modifyBtn, #deleteBtn, #backBtn\").addClass(\"d-none\").removeClass(\"d-inline-block\");\n");
        out.write("                        $(\".divTitle, .divContents\").addClass(\"form-control\").attr(\"contenteditable\", true);\n");
        out.write("                    });\n");
        out.write("\n");
        out.write("                    $(\"#cancelBtn, #confirmBtn\").on(\"click\", function () {\n");
        out.write("                        $(\"#confirmBtn, #cancelBtn\").toggleClass(\"d-none\", true);\n");
        out.write("                        $(\"#modifyBtn, #deleteBtn, #backBtn\").addClass(\"d-inline-block\").removeClass(\"d-none\");\n");
        out.write("                        $(\"[name = divTitle], [name = divContents]\").removeClass(\"form-control\").attr(\"contenteditable\", false);\n");
        out.write("                    });\n");
        out.write("\n");
        out.write("                    $(\"#cancelBtn\").on(\"click\", function () {\n");
        out.write("                        location.reload();\n");
        out.write("                    });\n");
        out.write("\n");
        out.write("                    $(\"#confirmBtn\").on(\"click\", function () {\n");
        out.write("                        $(\"[name = title]\").val($(\".divTitle\").html());\n");
        out.write("                        $(\"[name = contents]\").val($(\".divContents\").html());\n");
        out.write("                        $(\"<input>\").attr({\"type\": \"hidden\", \"name\": \"writer\"}).val(\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${post.writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\");\n");
        out.write("                        $(\"#modifyFrm\").submit();\n");
        out.write("                    });\n");
        out.write("                </script>\n");
        out.write("            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /WEB-INF/views/board/boardItem.jsp(132,27) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
