/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-09-17 02:35:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/sts3_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Day04_Board_eun/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1757403558891L));
    _jspx_dependants.put("jar:file:/C:/sts3_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Day04_Board_eun/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JSTL 날짜 포맷 라이브러리 -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("\r\n");
      out.write("<!-- JQuery -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"\r\n");
      out.write("	integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 -->\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css\"\r\n");
      out.write("	rel=\"stylesheet\"\r\n");
      out.write("	integrity=\"sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("	integrity=\"sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/board/detail.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("		");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\r\n");
        out.write("		");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write('\r');
        out.write('\n');
        out.write('	');
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/views/board/detail.jsp(35,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginId == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("			<script>\r\n");
        out.write("				alert(\"로그인 후 이용해주세요.\");\r\n");
        out.write("				location.href = \"/\";\r\n");
        out.write("			</script>\r\n");
        out.write("		");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("			<!-- 로그인 했을 때 -->\r\n");
        out.write("			<div class=\"container\">\r\n");
        out.write("				<!-- 컨텐츠 박스 ( 글 작성자 내용 ) -->\r\n");
        out.write("				<div class=\"contentsBox\">\r\n");
        out.write("					<!-- 제목 -->\r\n");
        out.write("					<div class=\"row title\">\r\n");
        out.write("						<div class=\"col\" contenteditable=\"false\" id=\"dto-title\"\r\n");
        out.write("							name=\"title\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</div>\r\n");
        out.write("					</div>\r\n");
        out.write("					<!-- 작성자 -->\r\n");
        out.write("					<div class=\"row writer\">\r\n");
        out.write("						<div class=\"col\" id=\"dto_writer\">\r\n");
        out.write("							<b>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.writer }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</b>\r\n");
        out.write("						</div>\r\n");
        out.write("					</div>\r\n");
        out.write("					<!-- 날짜, 조회수 -->\r\n");
        out.write("					<div class=\"row date-view\">\r\n");
        out.write("						<div class=\"col\">\r\n");
        out.write("							");
        if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("							| ");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.view_count }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\r\n");
        out.write("						</div>\r\n");
        out.write("					</div>\r\n");
        out.write("					<!-- 구분선 -->\r\n");
        out.write("					<hr>\r\n");
        out.write("					<!-- 글 내용 -->\r\n");
        out.write("					<div class=\"row contents\">\r\n");
        out.write("						<div class=\"col\" id=\"dto-contents\" contenteditable=\"false\"\r\n");
        out.write("							name=\"contents\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</div>\r\n");
        out.write("					</div>\r\n");
        out.write("					<!-- 버튼들 -->\r\n");
        out.write("					<div class=\"row btns\">\r\n");
        out.write("						<!-- 작성자 = 로그인한 사람 -->\r\n");
        out.write("						");
        if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("						<!-- 작성자 != 로그인한 사람 -->\r\n");
        out.write("						");
        if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("					</div>\r\n");
        out.write("					<!-- 글 내용 update form -->\r\n");
        out.write("					<form id=\"detail-Frm\" action=\"/board/update\" method=\"post\">\r\n");
        out.write("						<input type=\"hidden\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"seq\" id=\"dto_seq\">\r\n");
        out.write("						<input type=\"hidden\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"title\"\r\n");
        out.write("							id=\"dto_title\"> <input type=\"hidden\"\r\n");
        out.write("							value=\"");
        if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
          return true;
        out.write("\" name=\"contents\"\r\n");
        out.write("							id=\"dto_contents\">\r\n");
        out.write("					</form>\r\n");
        out.write("				</div>\r\n");
        out.write("\r\n");
        out.write("\r\n");
        out.write("				<!-- 댓글 박스 -->\r\n");
        out.write("				<div class=\"row replies g-0\">\r\n");
        out.write("					<!-- 댓글 div -->\r\n");
        out.write("					<div class=\"col replyDiv\" contenteditable=\"true\"></div>\r\n");
        out.write("					<!-- 댓글 등록 버튼 -->\r\n");
        out.write("					<div class=\"col-2 replyBtn\">\r\n");
        out.write("						<button class=\"btn btn-outline-dark\" id=\"replyBtn\">등록</button>\r\n");
        out.write("					</div>\r\n");
        out.write("					<!-- 댓글 있을시 출력 -->\r\n");
        out.write("					");
        if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("				</div>\r\n");
        out.write("			</div>\r\n");
        out.write("\r\n");
        out.write("			<script>\r\n");
        out.write("  // 삭제버튼 클릭시\r\n");
        out.write("  $(\"#deleteBtn\").on(\"submit\", function () {\r\n");
        out.write("    let form = $(\"#delete-Frm\");\r\n");
        out.write("\r\n");
        out.write("    // 제목/내용은 필요 없으니 제거\r\n");
        out.write("    $(\"#dto_title\").html(\"\");\r\n");
        out.write("    $(\"#dto_writer\").html(\"\");\r\n");
        out.write("\r\n");
        out.write("    form.submit();\r\n");
        out.write("  });\r\n");
        out.write("\r\n");
        out.write("  // update 버튼 클릭시\r\n");
        out.write("  $(\"#updateBtn\").on(\"click\", function () {\r\n");
        out.write("    // 제목 영역을 수정 가능하게 변경\r\n");
        out.write("    $(\"#dto-title\").attr(\"contenteditable\", true);\r\n");
        out.write("    $(\"#dto-contents\").attr(\"contenteditable\", true);\r\n");
        out.write("    $(\"#dto-contents\").focus();\r\n");
        out.write("\r\n");
        out.write("    // 버튼들 생기게 하고, 숨기기\r\n");
        out.write("    $(\"#okBtn\").removeClass(\"d-none\");\r\n");
        out.write("    $(\"#noBtn\").removeClass(\"d-none\");\r\n");
        out.write("    $(\"#updateBtn\").css(\"display\", \"none\");\r\n");
        out.write("    $(\"#deleteBtn\").css(\"display\", \"none\");\r\n");
        out.write("  });\r\n");
        out.write("\r\n");
        out.write("  // 목록으로 버튼 클릭시\r\n");
        out.write("  $(\"#listBtn\").on(\"click\", function () {\r\n");
        out.write("    window.location.href = \"/board/list\";\r\n");
        out.write("  });\r\n");
        out.write("\r\n");
        out.write("  // 수정완료 버튼 클릭시\r\n");
        out.write("  $(\"#okBtn\").on(\"click\", function () {\r\n");
        out.write("    let form = $(\"#detail-Frm\");\r\n");
        out.write("    form.attr(\"action\", \"/board/update\");\r\n");
        out.write("\r\n");
        out.write("    // 제목, 내용이 화면에 있는 경우 가져와서 넣기\r\n");
        out.write("    let title = $(\"#dto-title\").html();\r\n");
        out.write("    let contents = $(\"#dto-contents\").html();\r\n");
        out.write("\r\n");
        out.write("    // hidden input에 값 넣기\r\n");
        out.write("    $(\"#dto_title\").val(title);\r\n");
        out.write("    $(\"#dto_contents\").val(contents);\r\n");
        out.write("\r\n");
        out.write("    form.submit();\r\n");
        out.write("  });\r\n");
        out.write("\r\n");
        out.write("  // 취소버튼 클릭시\r\n");
        out.write("  $(\"#noBtn\").on(\"click\", function () {\r\n");
        out.write("    // 제목 영역을 수정 불가능하게 변경\r\n");
        out.write("    $(\"#dto-title\").attr(\"contenteditable\", false);\r\n");
        out.write("    $(\"#dto-contents\").attr(\"contenteditable\", false);\r\n");
        out.write("\r\n");
        out.write("    // 다시 원래 페이지로 돌아가게 하기\r\n");
        out.write("    window.location.href = \"/board/detail?seq=\" + $(\"#dto_seq\").val();\r\n");
        out.write("  });\r\n");
        out.write("\r\n");
        out.write("  $(function () {\r\n");
        out.write("    // 댓글 등록시\r\n");
        out.write("    $(\"#replyBtn\").on(\"click\", function () {\r\n");
        out.write("      let contents = $(\".replyDiv\").html();\r\n");
        out.write("      // JSP라면 아래처럼 null/빈값 방지 (JSTL 사용)\r\n");
        out.write("      let parent_seq = ");
        if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fotherwise_005f0, _jspx_page_context))
          return true;
        out.write(";\r\n");
        out.write("\r\n");
        out.write("      $.ajax({\r\n");
        out.write("        url: \"/reply/insert\",\r\n");
        out.write("        method: \"post\",\r\n");
        out.write("        data: {\r\n");
        out.write("          contents: contents,\r\n");
        out.write("          parent_seq: parent_seq\r\n");
        out.write("        }\r\n");
        out.write("      }).done(function (resp) {\r\n");
        out.write("        // 댓글 버튼\r\n");
        out.write("        let btnsHtml =\r\n");
        out.write("            '<div class=\"col-12 replyBtns\">' +\r\n");
        out.write("            '<button type=\"button\" class=\"btn btn-outline-dark replyOkBtn d-none\" ' +\r\n");
        out.write("            'data-reply-seq=\"' + resp.seq + '\" data-parent-seq=\"' + resp.parent_seq + '\">수정완료</button>' +\r\n");
        out.write("            '<button type=\"button\" class=\"btn btn-outline-dark replyNoBtn d-none\">취소</button>' +\r\n");
        out.write("            '<button type=\"button\" class=\"btn btn-outline-dark replyUpdateBtn\">수정</button>' +\r\n");
        out.write("            '<button type=\"button\" class=\"btn btn-outline-dark replyDeleteBtn\" ' +\r\n");
        out.write("            'data-reply-seq=\"' + resp.seq + '\" data-parent-seq=\"' + resp.parent_seq + '\">삭제</button>' +\r\n");
        out.write("            '<input type=\"hidden\" class=\"reply_contents\" value=\"' + resp.contents + '\" name=\"contents\">' +\r\n");
        out.write("            '<input type=\"hidden\" class=\"reply_seq\" value=\"' + resp.seq + '\" name=\"seq\">' +\r\n");
        out.write("            '<input type=\"hidden\" class=\"parent_seq\" value=\"' + resp.parent_seq + '\" name=\"parent_seq\">' +\r\n");
        out.write("            '</div>';\r\n");
        out.write("            \r\n");
        out.write("     	// 댓글 HTML\r\n");
        out.write("        let newReplyHtml =\r\n");
        out.write("          '<div class=\"replyBlock\">' +\r\n");
        out.write("          '<div class=\"col-12 replyWriter\"><b>' + resp.writer + '</b></div>' +\r\n");
        out.write("          '<div class=\"col-12 replyContentsDiv\" contenteditable=\"false\">' + resp.contents + '</div>' +\r\n");
        out.write("          '<div class=\"col-12 replyWrite_date\">' + resp.write_date + '</div>' +\r\n");
        out.write("          btnsHtml +\r\n");
        out.write("          '<hr id=\"replyHr\">' +\r\n");
        out.write("          '</div>';\r\n");
        out.write("\r\n");
        out.write("        // 댓글 목록에 추가\r\n");
        out.write("        $(\".replyBtn\").after(newReplyHtml);\r\n");
        out.write("        // 댓글 입력창 비우기\r\n");
        out.write("        $(\".replyDiv\").html(\"\");\r\n");
        out.write("        \r\n");
        out.write("      });\r\n");
        out.write("    });\r\n");
        out.write("\r\n");
        out.write("    // 댓글 삭제버튼 클릭시\r\n");
        out.write("    $(document).on(\"click\", \".replyDeleteBtn\", function () {\r\n");
        out.write("      let replySeq = $(this).data(\"reply-seq\");   // 댓글 고유 번호\r\n");
        out.write("      let parentSeq = $(this).data(\"parent-seq\"); // 게시글 번호\r\n");
        out.write("      let btn = this; // 버튼 참조 저장\r\n");
        out.write("\r\n");
        out.write("      $.ajax({\r\n");
        out.write("        url: \"/reply/delete\",\r\n");
        out.write("        method: \"POST\",\r\n");
        out.write("        data: {\r\n");
        out.write("          seq: replySeq,\r\n");
        out.write("          parent_seq: parentSeq\r\n");
        out.write("        }\r\n");
        out.write("      }).done((resp) => {\r\n");
        out.write("    	  if (resp === \"success\") {\r\n");
        out.write("    		  	const replyBlock = $(btn).closest(\".replyBlock\");\r\n");
        out.write("    		    replyBlock.remove();\r\n");
        out.write("    		  }\r\n");
        out.write("      });\r\n");
        out.write("    });\r\n");
        out.write("\r\n");
        out.write("    // 댓글 수정버튼 클릭시\r\n");
        out.write("    $(document).on(\"click\", \".replyUpdateBtn\", function () {\r\n");
        out.write("      const replyBlock = $(this).closest(\".replyBlock\");\r\n");
        out.write("      // 버튼 생기게 하고 없애기\r\n");
        out.write("      replyBlock.find(\".replyOkBtn\").removeClass(\"d-none\");\r\n");
        out.write("      replyBlock.find(\".replyNoBtn\").removeClass(\"d-none\");\r\n");
        out.write("      replyBlock.find(\".replyUpdateBtn\").addClass(\"d-none\");\r\n");
        out.write("      replyBlock.find(\".replyDeleteBtn\").addClass(\"d-none\");\r\n");
        out.write("\r\n");
        out.write("      replyBlock.find(\".replyContentsDiv\").attr(\"contenteditable\", true).focus();\r\n");
        out.write("    });\r\n");
        out.write("\r\n");
        out.write("    // 댓글 취소버튼 클릭시\r\n");
        out.write("    $(document).on(\"click\", \".replyNoBtn\", function () {\r\n");
        out.write("      const replyBlock = $(this).closest(\".replyBlock\");\r\n");
        out.write("      // contents 내용 다시 옮겨 담기\r\n");
        out.write("      let replyContentsDiv = replyBlock.find(\".replyContentsDiv\");\r\n");
        out.write("      replyContentsDiv.html(replyBlock.find(\".reply_contents\").val());\r\n");
        out.write("\r\n");
        out.write("      // 버튼 생기게 하고 없애기\r\n");
        out.write("      replyBlock.find(\".replyOkBtn\").addClass(\"d-none\");\r\n");
        out.write("      replyBlock.find(\".replyNoBtn\").addClass(\"d-none\");\r\n");
        out.write("      replyBlock.find(\".replyUpdateBtn\").removeClass(\"d-none\");\r\n");
        out.write("      replyBlock.find(\".replyDeleteBtn\").removeClass(\"d-none\");\r\n");
        out.write("\r\n");
        out.write("      // Div 수정 못하게 막기\r\n");
        out.write("      replyContentsDiv.attr(\"contenteditable\", false);\r\n");
        out.write("    });\r\n");
        out.write("\r\n");
        out.write("    // 댓글 수정완료 버튼 클릭시\r\n");
        out.write("    $(document).on(\"click\", \".replyOkBtn\", function () {\r\n");
        out.write("      const replyBlock = $(this).closest(\".replyBlock\");\r\n");
        out.write("      // 버튼에 저장된 데이터 꺼내기\r\n");
        out.write("      let reply_seq = $(this).data(\"reply-seq\");\r\n");
        out.write("      let parent_seq = $(this).data(\"parent-seq\");\r\n");
        out.write("\r\n");
        out.write("      // 버튼 생기게 하고 없애기\r\n");
        out.write("      replyBlock.find(\".replyOkBtn\").addClass(\"d-none\");\r\n");
        out.write("      replyBlock.find(\".replyNoBtn\").addClass(\"d-none\");\r\n");
        out.write("      replyBlock.find(\".replyUpdateBtn\").removeClass(\"d-none\");\r\n");
        out.write("      replyBlock.find(\".replyDeleteBtn\").removeClass(\"d-none\");\r\n");
        out.write("\r\n");
        out.write("      // 수정 막기\r\n");
        out.write("      replyBlock.find(\".replyContentsDiv\").attr(\"contenteditable\", false);\r\n");
        out.write("\r\n");
        out.write("      // 내용 담기\r\n");
        out.write("      let replyContentsDiv = replyBlock.find(\".replyContentsDiv\");\r\n");
        out.write("      let contents = replyContentsDiv.html().trim();\r\n");
        out.write("\r\n");
        out.write("      $.ajax({\r\n");
        out.write("        url: \"/reply/update\",\r\n");
        out.write("        method: \"post\",\r\n");
        out.write("        data: {\r\n");
        out.write("          \"contents\": contents,\r\n");
        out.write("          \"seq\": reply_seq\r\n");
        out.write("        }\r\n");
        out.write("      }).done(function () {\r\n");
        out.write("    	  replyContentsDiv.html(contents);\r\n");
        out.write("      });\r\n");
        out.write("    });\r\n");
        out.write("  });\r\n");
        out.write("</script>\r\n");
        out.write("\r\n");
        out.write("		");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
    // /WEB-INF/views/board/detail.jsp(61,7) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.create_at}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/views/board/detail.jsp(61,7) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy-MM-dd HH:mm:ss");
    int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
    // /WEB-INF/views/board/detail.jsp(76,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginId == dto.writer }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\r\n");
        out.write("							<div class=\"col btns text-end\">\r\n");
        out.write("								<form id=\"delete-Frm\" action=\"/board/delete\" method=\"post\">\r\n");
        out.write("									<button type=\"button\" class=\"btn btn-dark d-none\" id=\"noBtn\">취소</button>\r\n");
        out.write("									<button type=\"button\" class=\"btn btn-dark d-none\" id=\"okBtn\">수정완료</button>\r\n");
        out.write("\r\n");
        out.write("									<button class=\"btn btn-dark\" id=\"deleteBtn\">삭제하기</button>\r\n");
        out.write("									<input type=\"hidden\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"seq\"\r\n");
        out.write("										id=\"dto_seq2\">\r\n");
        out.write("\r\n");
        out.write("									<button type=\"button\" class=\"btn btn-dark\" id=\"updateBtn\">수정하기</button>\r\n");
        out.write("									<button type=\"button\" class=\"btn btn-dark\" id=\"listBtn\">목록으로</button>\r\n");
        out.write("								</form>\r\n");
        out.write("							</div>\r\n");
        out.write("						");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
    // /WEB-INF/views/board/detail.jsp(93,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginId != dto.writer }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("							<div class=\"col btns text-end\">\r\n");
        out.write("								<button type=\"button\" class=\"btn btn-dark\" id=\"listBtn\">목록으로</button>\r\n");
        out.write("							</div>\r\n");
        out.write("						");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
    // /WEB-INF/views/board/detail.jsp(104,14) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.contents}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
    // /WEB-INF/views/board/detail.jsp(119,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("replyDto");
    // /WEB-INF/views/board/detail.jsp(119,5) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/board/detail.jsp(119,5) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("						<div class=\"replyBlock\">\r\n");
          out.write("							<div class=\"col-12 replyWriter\">\r\n");
          out.write("								<b>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${replyDto.writer}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</b>\r\n");
          out.write("							</div>\r\n");
          out.write("							<div class=\"col-12 replyContentsDiv\" contenteditable=\"false\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${replyDto.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</div>\r\n");
          out.write("							<div class=\"col-12 replyWrite_date\">\r\n");
          out.write("								");
          if (_jspx_meth_fmt_005fformatDate_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("							</div>\r\n");
          out.write("\r\n");
          out.write("							");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("\r\n");
          out.write("							<hr id=\"replyHr\">\r\n");
          out.write("						</div>\r\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
    }
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    _jspx_th_fmt_005fformatDate_005f1.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fformatDate_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/board/detail.jsp(126,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f1.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${replyDto.write_date}", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/views/board/detail.jsp(126,8) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fformatDate_005f1.setPattern("yyyy-MM-dd HH:mm:ss");
    int _jspx_eval_fmt_005fformatDate_005f1 = _jspx_th_fmt_005fformatDate_005f1.doStartTag();
    if (_jspx_th_fmt_005fformatDate_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /WEB-INF/views/board/detail.jsp(130,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginId == replyDto.writer}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("								<div class=\"col-12 replyBtns\">\r\n");
        out.write("									<button type=\"button\"\r\n");
        out.write("										class=\"btn btn-outline-dark replyOkBtn d-none\"\r\n");
        out.write("										data-reply-seq=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${replyDto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" data-parent-seq=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">수정완료</button>\r\n");
        out.write("									<button type=\"button\"\r\n");
        out.write("										class=\"btn btn-outline-dark replyNoBtn d-none\">취소</button>\r\n");
        out.write("\r\n");
        out.write("									<button type=\"button\"\r\n");
        out.write("										class=\"btn btn-outline-dark replyUpdateBtn\">수정</button>\r\n");
        out.write("									<button class=\"btn btn-outline-dark replyDeleteBtn\"\r\n");
        out.write("										data-reply-seq=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${replyDto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" data-parent-seq=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">삭제</button>\r\n");
        out.write("\r\n");
        out.write("									<input type=\"hidden\" class=\"reply_contents\"\r\n");
        out.write("										value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${replyDto.contents}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" name=\"contents\"> <input\r\n");
        out.write("										type=\"hidden\" class=\"reply_seq\" name=\"seq\"\r\n");
        out.write("										value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${replyDto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"> <input type=\"hidden\"\r\n");
        out.write("										class=\"parent_seq\" name=\"parent_seq\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("								</div>\r\n");
        out.write("							");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fotherwise_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fotherwise_005f0);
    // /WEB-INF/views/board/detail.jsp(219,23) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.seq}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/views/board/detail.jsp(219,23) name = default type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setDefault("0");
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fdefault_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }
}
