/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.108
 * Generated at: 2025-09-16 11:43:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.members;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mypage_005fupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1757403558891L));
    _jspx_dependants.put("jar:file:/C:/sts3_workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Day04_Board_eun/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<!-- JQuery -->\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"\r\n");
      out.write("            integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 부트스트랩 -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css\" rel=\"stylesheet\"\r\n");
      out.write("          integrity=\"sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr\" crossorigin=\"anonymous\">\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js\"\r\n");
      out.write("            integrity=\"sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q\"\r\n");
      out.write("            crossorigin=\"anonymous\"></script>\r\n");
      out.write("<!-- 다음 우편번호 API -->\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/members/mypage_update.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fchoose_005f0.setParent(null);
    int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
    if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("		");
        if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\r\n");
        out.write("		");
        if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
          return true;
        out.write('\r');
        out.write('\n');
        out.write('	');
        int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    // /WEB-INF/views/members/mypage_update.jsp(31,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginId == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
    if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("			<script>\r\n");
        out.write("				alert(\"로그인 후 이용해주세요.\");\r\n");
        out.write("				location.href = \"/\";\r\n");
        out.write("			</script>\r\n");
        out.write("		");
        int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
    int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
    if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("			<div class=\"container mt-3\">\r\n");
        out.write("				<div class=\"row\">\r\n");
        out.write("					<div\r\n");
        out.write("						class=\"col mb-2 d-flex justify-content-left align-items-center\">\r\n");
        out.write("						<a href=\"/members//mypage\" class=\"card-link me-3\"> &lt;</a>\r\n");
        out.write("						<h2 class=\"card-title\">계정 정보</h2>\r\n");
        out.write("					</div>\r\n");
        out.write("				</div>\r\n");
        out.write("				<!-- 계정 정보 -->\r\n");
        out.write("				<form action=\"/members/update\" method=\"post\">\r\n");
        out.write("					<div class=\"card account row mt-3\">\r\n");
        out.write("						<div class=\"card-body\">\r\n");
        out.write("							<div\r\n");
        out.write("								class=\"col d-flex justify-content-between align-items-center mb-2\">\r\n");
        out.write("								<h6 class=\"card-subtitle text-body-secondary\">사용자 ID</h6>\r\n");
        out.write("								<h6>");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</h6>\r\n");
        out.write("							</div>\r\n");
        out.write("\r\n");
        out.write("							<div\r\n");
        out.write("								class=\"col d-flex justify-content-between align-items-center mb-2\">\r\n");
        out.write("								<h6 class=\"card-subtitle text-body-secondary\">전화번호</h6>\r\n");
        out.write("								<input type=\"text\" class=\"input_style\" id=\"phone\" name=\"phone\"\r\n");
        out.write("									value=\"\">\r\n");
        out.write("							</div>\r\n");
        out.write("\r\n");
        out.write("							<div\r\n");
        out.write("								class=\"col d-flex justify-content-between align-items-center mb-2\">\r\n");
        out.write("								<h6 class=\"card-subtitle text-body-secondary\">이메일 주소</h6>\r\n");
        out.write("								<input type=\"text\" class=\"input_style\" id=\"email\" name=\"email\"\r\n");
        out.write("									value=\"\">\r\n");
        out.write("							</div>\r\n");
        out.write("\r\n");
        out.write("							<div\r\n");
        out.write("								class=\"col d-flex justify-content-between align-items-center mb-2\">\r\n");
        out.write("								<h6 class=\"card-subtitle text-body-secondary\">우편번호</h6>\r\n");
        out.write("								<div\r\n");
        out.write("									class=\"post_input d-flex justify-content-between align-items-center\">\r\n");
        out.write("									<input type=\"text\" class=\"input_style me-1\" id=\"postcode\"\r\n");
        out.write("										name=\"postcode\" value=\"\" style=\"width: 90%\"> <input\r\n");
        out.write("										type=\"button\" onclick=\"sample4_execDaumPostcode()\" value=\"찾기\"\r\n");
        out.write("										class=\"btn p-0\">\r\n");
        out.write("								</div>\r\n");
        out.write("							</div>\r\n");
        out.write("\r\n");
        out.write("							<div\r\n");
        out.write("								class=\"col d-flex justify-content-between align-items-center mb-2\">\r\n");
        out.write("								<h6 class=\"card-subtitle text-body-secondary\">주소</h6>\r\n");
        out.write("								<input type=\"text\" class=\"input_style\" id=\"address1\"\r\n");
        out.write("									name=\"address1\" value=\"\">\r\n");
        out.write("							</div>\r\n");
        out.write("\r\n");
        out.write("							<div\r\n");
        out.write("								class=\"col d-flex justify-content-between align-items-center mb-2\">\r\n");
        out.write("								<h6 class=\"card-subtitle text-body-secondary\">상세 주소</h6>\r\n");
        out.write("								<input type=\"text\" class=\"input_style\" id=\"address2\"\r\n");
        out.write("									name=\"address2\" value=\"\">\r\n");
        out.write("							</div>\r\n");
        out.write("\r\n");
        out.write("							<div\r\n");
        out.write("								class=\"col d-flex justify-content-between align-items-center mb-2\">\r\n");
        out.write("								<h6 class=\"card-subtitle text-body-secondary\">본인확인</h6>\r\n");
        out.write("								<h6>\r\n");
        out.write("									본인확인 완료 <img src=\"/img/check.png\" style=\"height: 18px\">\r\n");
        out.write("								</h6>\r\n");
        out.write("							</div>\r\n");
        out.write("\r\n");
        out.write("							<div\r\n");
        out.write("								class=\"col d-flex justify-content-center align-items-center mb-2\">\r\n");
        out.write("								<button type=\"submit\" class=\"join_btn\" id=\"updateBtn\">수정완료</button>\r\n");
        out.write("							</div>\r\n");
        out.write("						</div>\r\n");
        out.write("					</div>\r\n");
        out.write("				</form>\r\n");
        out.write("			</div>\r\n");
        out.write("\r\n");
        out.write("			<script>\r\n");
        out.write("			$(function(){\r\n");
        out.write("				$.ajax({\r\n");
        out.write("					url:\"/members/mypage_update_data\"\r\n");
        out.write("				}).done(function(resp){\r\n");
        out.write("					$(\"#phone\").val(resp.phone);\r\n");
        out.write("	                $(\"#email\").val(resp.email || \"\");\r\n");
        out.write("	                $(\"#postcode\").val(resp.zipcode || \"\");\r\n");
        out.write("	                $(\"#address1\").val(resp.address1 || \"\");\r\n");
        out.write("	                $(\"#address2\").val(resp.address2 || \"\");\r\n");
        out.write("				})\r\n");
        out.write("			})\r\n");
        out.write("			\r\n");
        out.write("			// 다음 우편번호 API\r\n");
        out.write("			function sample4_execDaumPostcode() {\r\n");
        out.write("				new daum.Postcode({\r\n");
        out.write("					oncomplete : function(data) {\r\n");
        out.write("						// 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분.\r\n");
        out.write("						// 우편번호와 주소 정보를 해당 필드에 넣는다.\r\n");
        out.write("						$(\"#postcode\").val(data.zonecode);\r\n");
        out.write("						$(\"#address1\").val(data.roadAddress);\r\n");
        out.write("					}\r\n");
        out.write("				}).open();\r\n");
        out.write("			}\r\n");
        out.write("			\r\n");
        out.write("			// (유효성 검사)\r\n");
        out.write("			$(\"form\").on(\"submit\", function() {\r\n");
        out.write("				// 정규식\r\n");
        out.write("				let regexName = /^[a-zA-Z가-힣]{2,6}$/\r\n");
        out.write("				let regexPhone = /^010[0-9]{8}$|^010-[0-9]{4}-[0-9]{4}$/;\r\n");
        out.write("				let regexEmail = /^[\\da-z_]{4,12}@[\\w\\d]+(\\.com|\\.co\\.kr)$/;\r\n");
        out.write("\r\n");
        out.write("				// phone\r\n");
        out.write("				let phone = $(\"#phone\").val();\r\n");
        out.write("				if (phone == \"\") {\r\n");
        out.write("					alert(\"전화번호를 입력해주세요.\\n(예:01012341234 또는 010-1234-1234)\");\r\n");
        out.write("					$(\"#phone\").focus();\r\n");
        out.write("					return false;\r\n");
        out.write("				}\r\n");
        out.write("\r\n");
        out.write("				if (!regexPhone.test(phone)) {\r\n");
        out.write("					alert(\"전화번호 형식이 맞지 않습니다.\\n(예:01012341234 또는 010-1234-1234)\");\r\n");
        out.write("					$(\"#phone\").focus();\r\n");
        out.write("					return false;\r\n");
        out.write("				}\r\n");
        out.write("\r\n");
        out.write("				// 이메일\r\n");
        out.write("				let email = $(\"#email\").val();\r\n");
        out.write("\r\n");
        out.write("				if (email != \"\") {\r\n");
        out.write("					if (!regexEmail.test(email)) {\r\n");
        out.write("						alert(\"이메일 형식이 올바르지 않습니다.\\n예시 : 영문 및 숫자@naver.com\\n예시2 : 영문 및 숫자@naver.co.kr\");\r\n");
        out.write("						$(\"#email\").focus();\r\n");
        out.write("						return false;\r\n");
        out.write("					}\r\n");
        out.write("				}\r\n");
        out.write("			})\r\n");
        out.write("			</script>\r\n");
        out.write("		");
        int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
    return false;
  }
}
